version: 1.0.{build}
image: Visual Studio 2019

init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
      Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }
    else
    {
      Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
    }

before_build:
  - cmd: nuget restore src/MonsterMonitor.sln

build:
  project: src/MonsterMonitor.sln

after_build:
- cmd: 7z a MonsterMonitor.zip %APPVEYOR_BUILD_FOLDER%/src/MonsterMonitor/bin/Debug/*

artifacts:
- path: MonsterMonitor.zip
  name: MonsterMonitor.zip

deploy:
- provider: GitHub
  auth_token:
    secure: %GITHUB_TOKEN%
  artifact: MonsterMonitor.zip
  on:
    APPVEYOR_REPO_TAG: true